### ISSUE TITLE
Allow translation for nested files

### ISSUE THREAD

**Issue by finaldzn** [pandodao/i18n-cli#2]
Hello I wanted to try your cli but it doesn't work with nested translations.

Is it possible to add it ? 

Thank you

**Comment by lyricat** [comment]
Sure. it's possible. Will do it.

**Comment by lyricat** [comment]
adding nested translations support https://github.com/pandodao/i18n-cli/commit/45b4d0c0b410d716e44c740ad69f4798374b8a3e

hope you like it. :)

**Comment by finaldzn** [comment]
thank you, will try it and let you know how it goes ! :)

**Comment by sinchang** [comment]
Hi @lyricat could you release a new version to support the nested json?

**Comment by lyricat** [comment]
> Hi @lyricat could you release a new version to support the nested json?

ah, I forgot that. It is ready now v0.0.7

**Comment by finaldzn** [comment]
fixed in 45b4d0c
