### ISSUE TITLE
What is --independent?

### ISSUE THREAD

**Issue by psarno** [pandodao/i18n-cli#3]
I am running under Windows.

Your screenshot shows MacOS running it from the command-line without the --independent parameter, but the usage documentatation states:

```
export OPENAI_API_KEY=YOUR_API_KEY
i18n-cli translate \
  --dir ./locales \
  --source ./locales/en-US.json \
  --independent ./independent.json
```

Since I am under Windows, I am using `SET OPENAI_API_KEY=` instead.

After this, I attempt to run:

`i18n-cli translate --dir ./i18n --source ./i18n/en.json`

This results in two errors:

> failed to get language: independent.json
> failed to get language: test.json

First, what is independent.json?    The documents don't say much about what this is or what it is supposed to contain.   Right now I have three files in my i18n folder ... en.json, which has all the translations, and two empty ones, fr.json and es.json, that I would like populated.  Is that correct?

What is independent.json?   And for that matter, what is test.json?

If I create an empty independent.json file to test, and then run:

`i18n-cli translate --dir ./i18n --source ./i18n/en.json --independent ./i18n/independent.json`

I get the same error as above.

My en.json is structured as such ... is this not what this program is meant to deal with?

```
{
  "LOGIN": {
    "FORGOT_USERNAME": "Forgot your username?",
    "FORGOT_PASSWORD": "Forgot your password?",
  },
  "CUSTOMERSEARCH": {
    "CONTACT_EMAIL": "Contact Email",
    "BILLING_EMAIL": "Billing Email",
  }
}
```

**Comment by lyricat** [comment]
Hi, independent.json is optional. You can ignore the  parameter.

> failed to get language: independent.json
> failed to get language: test.json

You got the error message because they are in the i18n folder. please remove them and make sure the json file's name is [language_code].json. e.g. `en.json`, `en-US.json`, `ja.json`

for example, the "locales" folder in the repo:

```bash
ls locales/
en-US.json  ja-JP.json
```

and run 

```bash
i18n-cli translate --dir locales --source locales/en-US.json
```

**Comment by psarno** [comment]
@lyricat Something is still wrong.

I have two empty files in my i18n directory, which is a subfolder under assets.

Within assets I have an en.json file that contains my English dictionary.   This file contains over 8,000 translations in it.

I run the following in the assets folder:

`i18n-cli translate --dir i18n --source en.json`

This shows me:

![image](https://github.com/pandodao/i18n-cli/assets/18640860/38b14304-0d96-4bea-b9d5-313a0704d407)

So clearly 155 is wrong, it's over 8,500.

And the resulting two files in i18n, which are en-US.json and fr.json, now simply contain the following:

> {}

**Comment by lyricat** [comment]
can you show me content of en.json?

**Comment by psarno** [comment]
> can you show me content of en.json?

I added the structure in the initial post.  It's nested JSON, which I think might be why this isn't working ... the 155 may be the top level keys and not all the actual translation data.

If this isn't supported, let me know.

It looks basically like this:

![image](https://github.com/pandodao/i18n-cli/assets/18640860/e01ad9f2-3bd5-4649-b8d9-d33c8da55a68)

**Comment by lyricat** [comment]
@psarno Hi, the nested JSON is supported since https://github.com/pandodao/i18n-cli/releases/tag/v0.0.7
